version: '3.3'

services:
  mongo: 
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017